
FROM php:8-apache
RUN cat /etc/issue

RUN docker-php-ext-install pdo pdo_mysql
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli

RUN apt-get update && apt-get upgrade
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -

RUN apt-get install -y nodejs
RUN apt-get install -y git

RUN npm install -g npm


WORKDIR /app
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

ADD ./ .

RUN composer install
RUN composer require laravel/ui --dev
RUN php artisan ui react
RUN npm install
RUN npm run dev

CMD php artisan serve --host=0.0.0.0

EXPOSE 8000

